-- =============================================================================
-- Referencia legacy / fragmentos. El bootstrap real esta en backend/server.js
-- dentro de `ensureSchema()` (CREATE IF NOT EXISTS + ALTER idempotentes).
--
-- La tabla `transactions` en produccion incluye (entre otras):
--   customer_name, invoice_number, items, subtotal, sales_tax_paid, sales_tax_owed,
--   tax, payment_method, location, source_file_name, extraction_status, review_status,
--   import_batch_id, source_row_number, vendor_id, project_id
--
-- `review_flags` tiene FK a transactions(id) ON DELETE CASCADE cuando se crea con
-- el codigo actual.
-- =============================================================================

-- Ejemplo de extension antigua (solo si faltan columnas en una base muy vieja):
-- ALTER TABLE transactions
-- ADD COLUMN customer_name VARCHAR(255) NULL AFTER vendor,
-- ADD COLUMN invoice_number VARCHAR(100) NULL AFTER transaction_date;
