-- =============================================================================
-- NOTA: este archivo NO es el esquema operativo de Greg Tracker actual.
-- La fuente de verdad es `ensureSchema()` en `backend/server.js` (arranque Node).
-- Se deja aqui como referencia historica del diseno inicial; no ejecutar ciegamente
-- sobre una base ya usada por la app (nombres de tablas y columnas difieren).
-- =============================================================================
-- Ver tambien: `migration_phase1.sql` (fragmentos legacy) y `README.md` en esta carpeta.
